#!/bin/sh

# resize last partition
parted -s /dev/mmcblk0 resizepart 3 100%

# create piejam filesystem
mkfs.ext2 -q -F -L piejam /dev/mmcblk0p3

# mount
mkdir /piejam
echo "/dev/mmcblk0p3	/piejam		ext2	rw,defaults	0	2" >> /etc/fstab
mount /dev/mmcblk0p3 /piejam

# remove the script, because it's a one time action on first boot
rm "/etc/init.d/`basename $0`"
